language: scala
scala:
  - 2.12.2

script:
- sbt  ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
after_success:
- bash <(curl -s https://codecov.io/bash)
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then sbt ++$TRAVIS_SCALA_VERSION releaseEarly;
  fi

before_install:
- openssl aes-256-cbc -K $encrypted_1d76f4871d2b_key -iv $encrypted_1d76f4871d2b_iv
  -in travis/secrets.tar.enc -out travis/local.secrets.tar -d;
- tar xv -C travis -f travis/local.secrets.tar;
- ls travis
- ls ./travis
- pwd
env:
  global:
  - secure: LMVjXwcvpDfuX5ckoaTWEEoSzrZDx+MjeZD3yBvIzk0BJpCp/uFMLq4IkiPJCUgP4upHcEbUHplxkQdSVvFchodfE4aBmICci0/yPdxwVG/a7ccQAC+AEJUG5/OmOt4K5qfr2ksc3xQh2//HJcFVvUZLVPMYpBeMugytjxzVYAWeqwnIjc5GkarXek2YiIGls1s/7ZVHoyRh0154cGJs2YoF0/0wUmcTv9gRHIvCUexiXUKgik3/oR7bQKQkwYT0w4ywKWc4oWYY6u3HHSVj4TolU9UFNFieIIicBPP81NSMRZOU/FLKt5Wk/ASQw7CtwVRH3cjSOnMiaPGWVLs1vyD/lyFTFC3gqnJHHyod8a0A7kHJ2Q+mfGObYFQ3+i6qCZrOPLzXySG5I1henEafCJNqaMppp7h0bBvd2Zr/3PId36HLn4b8JvUf4RY3MzlHy1eXLcz6Y9gS+aiTxiE93GOIhjw00CTNQftFLOxHPEitjz837GiocrB5drYXyyUSbTtyhmNtw/zsnYJnsnd4m7WkLuryIcKGOvZaIS3HWnEQNJLMOjmfdU7n+HOqkFYGIrBpXSCqWuRsr1zCluGXiNjD4OPpdH3kb1OEannRGpaBmcjmuO1quGTOtiI+K9+hhjzFaxtiS4fzJr1j5Cbj3tpmWsny2UDQtpJSOwicUxc=
  - secure: rJadDx5tvs5xSBciA591TNqeFYHk3BW7VTxfTEuju9ZfttCxmv8Hi3dmwVhbLjuXyP69G9KEvHybVZM868gQM+E9KjPAAzk3TPsz2TipTmu6njfQuck4NuFz1JiwwRU7nBXO//einwhp5UFBA0SOOMorU5RnlGNaocsTXJ5iZsbobtLR46IeLD4rJDRmQPg8fQ956cOGSxOLcrF7bnMUX/vzpdhkG21f679KfoM1W8lWoja/o3ESIPAq2jevOPbxLy7pP4q4nJsVAY2id8x/ExXaSJ2vmJFlFRorIdw+ANiHsZ9bS2YTVT6KXWxnuVGPvURhFCeTsR+of2f0FD70B19q/wnP9DTsgsfIYTJKA3yTI/VMKuJBj6ksxl2AoACFPJacqRLyWGjRVfjMNAagQ6aReZQxJysA9sK9PKsRl4z8pHiFw5LnXLYfaidZJzUnPq0Nz3mT3DycldptNrKgKlfV1G9qnFrDLr2fm09zrfTOKvq3IA/CtgRzdC7E48bvzIt6CmYnISDWzpGm9Ak69eUAxUCSt8xGJ49BasqU8MIsIZGIBvYvN3xp2R9cIOuOC8oQd+Rwa5hxjpAH2jTBcCrSB3xkNkishgSSBFGkQhtehustQEtWMpnduoRAVrb+GEHXcsxWxZjg/UwR6Y1CulZWnuLZIVriFt7AUE/U9lk=
  - secure: PgcfIwAA5xtjGjbqZXtJvaJChVjuQ5NpDCEQrqJjqHkkQhYfcul/83b1n4jSaL6fM2qwFSXo4G4gqO9CNKhe5fdeCzZGZKTQOrzkoVLbjTb9BjJpJS2/gaoyGyvVNWFWzm8NF9LMsutiIiIpu7sG/ActuicJnN9MmvE6zxPmXe4BGTKAC1VWZiY3XfNAxmwI546TEvt71DAYU91YdirTbb1b9lOtdF1QTPdHkju5JlpZj0ZgQH8LkQq+1ostshHZKxHlG6WNi0k0rDFU5sLOBgndj9wIrgEE7Vq2tYcN6Tldpox6gpcEaKvzxvJ0SdH5DCx4uQl8x0IxIWWZgJpjhy7VHhFHMwgdIlap4uQEd8QyuY7eNmbV1AMDAz3HJdnKsJE2tNrHXu9PsVIVok5HSiVY17vEPaIZDCcqx82ai2C/HlqAszXoBns+1qXqQ8ak9O26LvRRgNQNmdeaXTTtlRKsXHP0JpYhaLXQvPAo/YxgY9ra2daXYShocrcxBwD66GZeAV5Smm3N6MmYiNeVAtxG/44zKk6W+ZG0twZpsSkCUC7Q9u6OoEqC2vCh2dwuwu1xI21iX6zzhfoBARR/T437sHf5n7H4Lt3Hk7ZIDvpX/EJNyED7K4Lhhc9GwoGt9t0crDxdeVtzIX/q6FTTBf5bh/1FVwEyM8yclgODIRY=

